micronaut:
  application:
    name: demoClient
  grpc:
    server:
      port: 50052
      host: "0.0.0.0"
    channels:
      tokenApi:
        target: "http://localhost:50051"
        plaintext: true